module.exports = function (program) {
    program.version('1.1.0', '-v, --version', 'output the current version')
    program.command('init', 'define service and create folders to use it. \'-y\' to skip question with default values', { executableFile: 'lib/cmd/test.js'})
    program.command('reset [name]', 'redefine service configuration', { executableFile: 'lib/cmd/test.js'})
    program.command('test', 'do nothing. i guess...', { executableFile: 'lib/cmd/test.js'})
    program.command('system-get', 'get system information and configuration', { executableFile: 'lib/cmd/test.js'})
    program.command('service [name]', 'get service configuration values', { executableFile: 'lib/cmd/test.js'})
    program.command('destroy [name]', 'delete service, folder or configuration file', { executableFile: 'lib/cmd/test.js'})
    program.command('rm [name]', 'delete service, folder or configuration file', { executableFile: 'lib/cmd/test.js'})
    program.command('del [name]', 'delete service, folder or configuration file', { executableFile: 'lib/cmd/test.js'})
    program.command('new [name]', 'create a new version for the service', { executableFile: 'lib/cmd/test.js'})
    program.command('rollback [name], rb [name]', 'set to the previous version', { executableFile: 'lib/cmd/test.js'})
    program.command('rb [name]', 'see rollback', { executableFile: 'lib/cmd/test.js'})
    program.command('forward, fw', 'set to the next version', { executableFile: 'lib/cmd/test.js'})
}
